config/routes.rb
Rails.application.routes.draw do
  resources :timetables
  get 'talks/index'
  post 'talks/update', to: 'talks#update', as: 'talk_update'

  resources :calendars
  get 'sessions/new'

  get 'events/top'
  resources :infos
  resources :events
  get 'classroom/top/:nen/:room' => 'classroom#top'
  #get 'home/top'
  get '/', to: 'home#top'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/timetables_controller.rb
class TimetablesController < ApplicationController
  before_action :set_timetable, only: [:show, :edit, :update, :destroy]
  before_action :user_logged_in?, except:  [:index]

  layout 'kokuban'
  
  # GET /timetables
  # GET /timetables.json
  def index
    logout
    @nengapi = Date.today
    if Timetable.find_by(date: @nengapi) == nil
      @nengapi = 0
    end
  end

  # GET /timetables/1
  # GET /timetables/1.json
  
    

  # GET /timetables/new
  def new
    
    @timetable = Timetable.new
  end

  # GET /timetables/1/edit
  def edit
    
  end
  
  # POST /timetables
  # POST /timetables.json
  def create
    @timetable = Timetable.find_by(date: timetable_params[:nengapi].to_i)
    if @timetable == nil
      @timetable = Timetable.new(timetable_params)
    end
    @timetable.filename = timetable_params[:filename]
    if !timetable_params[:filename].present?
      @timetable.errors[:base] << 'ファイル名を入力してください'
      render 'new'
    elsif timetable_params[:filename].content_type != "application/pdf"
      @timetable.errors[:base] << 'PDF以外のファイルはアップロードできません'
      render 'new'
    else  
     File.open("app/assets/images/pdf/timetable/#{@timetable.date.strftime("%Y%m%d")}"+".pdf","w+b"){
        |f| f.write(timetable_params[:filename].read)
      } 
      @timetable.filename = @timetable.date.to_s + ".pdf" 

      respond_to do |format|
        if @timetable.save
          format.html { redirect_to @timetable, notice: '成功しました！' }
          format.json { render :show, status: :created, location: @timetable }
        else
          format.html { render :new }
          format.json { render json: @timetable.errors, status: :unprocessable_entity }
        end      
      end
    end   
  end

  # PATCH/PUT /timetables/1
  # PATCH/PUT /timetables/1.json
  def update
    respond_to do |format|
      if @timetable.update(timetable_params)
        format.html { redirect_to @timetable, notice: 'アップデートできました！' }
        format.json { render :show, status: :ok, location: @timetable }
      else
        format.html { render :edit }
        format.json { render json: @timetable.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /timetables/1
  # DELETE /timetables/1.json
  def destroy
    @timetable.destroy
    respond_to do |format|
      format.html { redirect_to timetables_url, notice: 'Timetable was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_timetable
      @timetable = Timetable.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def timetable_params
      params.require(:timetable).permit(:date, :filename)
    end
end

app/helpers/timetables_helper.rb
module TimetablesHelper
end

app/views/timetables/_form.html.erb
<%= form_with(model: timetable, local: true) do |form| %>
  <% if timetable.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(timetable.errors.count, "error") %> prohibited this timetable from being saved:</h2>

      <ul>
      <% timetable.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <br>
  <div class="field">
  <font color='white' size="4"><%= form.label :時間割PDF %>
    <%= form.file_field :filename %>
    <%= form.label :年月日 %>
    <%= form.date_select :date, id: :timetable_date %>
  </div>

  <div class="actions">
    <%= form.submit :完了 %>

  </div>
<% end %>

app/views/timetables/edit.html.erb
<font color="white"size="6">時間割編集画面</font>

<%= render 'form', timetable: @timetable %>

app/views/timetables/index.html.erb
<p id="notice"><%= notice %></p>
<!--<div style="height:600px; width:100%; overflow-y:scroll;">
-->
<font color='white' size="6">時間割</font>

<% if @nengapi != 0 %> 
<object data="<%= asset_path 'pdf/timetable/' + @nengapi.strftime("%Y%m%d") + '.pdf'%>"
 type="application/pdf" width="100%" height="600px"></object>
<% end %>
<!--</div>
-->
<br>
<br>
<font size="4"><%= link_to 'TOP画面へ' , '/', :style=>"color:white;" %>

<br>

<font size="4"><%= link_to '登録', new_timetable_path, :style=>"color:white;" %>

app/views/timetables/new.html.erb
<font color="white"size="6">時間割入力画面</font>

<%= render 'form', timetable: @timetable %>

app/views/timetables/show.html.erb
<p id="notice"><%= notice %></p>
<font color='white' size="6">確認画面</font>
<br>
<br>
<p>
  <font size="4" , color="white"><strong>年月日:</strong>
  <%= @timetable.date.strftime("%Y年%m月%d日") %></font>
</p>

<br>
<font size="3"><%= link_to '編集', edit_timetable_path(@timetable), :style=>"color:white;" %><br> 
<font size="3"><%= link_to '時間割画面に戻る', timetables_path, :style=>"color:white;" %></br>