config/routes.rb
Rails.application.routes.draw do
  resources :timetables
  get 'talks/index'
  post 'talks/update', to: 'talks#update', as: 'talk_update'

  resources :calendars
  get 'sessions/new'

  get 'events/top'
  resources :infos
  resources :events
  get 'classroom/top/:nen/:room' => 'classroom#top'
  #get 'home/top'
  get '/', to: 'home#top'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  layout 'kokuban'

  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :user_logged_in?, except: :top

  def top
    logout
    session[:return_path] = request.fullpath
    @naiyou = Event.where(eventday: DateTime.new(Date.today.year, Date.today.month, Date.today.day))
  end

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: '成功しました！' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: '成功しました！' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: '成功しました！' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:content, :eventday)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
  <br>
    <%= form.label :内容 , :style=>"color:white;" %>
    <%= form.text_field :content, id: :event_content %>
  </div>

  <div class="field">
    <%= form.label :行事日付 , :style=>"color:white;" %>
    <%= form.date_select :eventday,id: :event_eventday %>
  </div>

  <div class="actions">
    <%= form.submit :更新 %>
  </div>
<% end %>

app/views/events/edit.html.erb
<font color='white' size="5">行事の編集</font>
<br>
<%= render 'form', event: @event %>

<%= link_to '詳細', @event , :style=>"color:white;" %> |
<%= link_to '戻る', events_path , :style=>"color:white;" %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>



<font color='white' size="7">行事一覧
<br>
<br>
<table border="2">
  <thead>
    <tr>
      <th><font color='white' size="4">行事</th>
      <th><font color='white' size="4">日時</th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.content %></td>
        <td><%= event.eventday.strftime("%Y年 %m月 %d日") %></td>
        <td><%= link_to '詳細', event , :style=>"color:white;" %></td>
        <td><%= link_to '編集', edit_event_path(event) ,:style=>"color:white;" %></td>
        <td><%= link_to '削除', event, method: :delete, data: { confirm: '本当に削除しますか?' } ,:style=>"color:white;" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<tfoot>
    <tr><td colspan="2"></td></tr>
</tfoot>

<br>
<br>
<br>

<font color='white' size="4"><%= link_to '行事追加', new_event_path , :style=>"color:yellow;" %>

<br><font color='white' size="4"><%= link_to '戻る', events_top_path , :style=>"color:white;" %>

app/views/events/new.html.erb
<font color='white' size="5">行事の追加</font>

<%= render 'form', event: @event %>

<%= link_to '戻る', events_path , :style=>"color:white;" %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
<font color='white' size="3"><strong>行事:</strong>
  <%= @event.content %>
</p>

<p>
<font color='white' size="3"><strong>行事日付:</strong>
  <%= @event.eventday.strftime('%Y年%m月%d日') %>
</p>

<br>
<br>
<%= link_to '編集', edit_event_path(@event) , :style=>"color:white;" %> 
<%= link_to '戻る', events_path , :style=>"color:white;" %>

app/views/events/top.html.erb
<p id="notice"><%= notice %></p>
<h1><font color='white' size="7"><%= Date.today.mon %>月 <%= Date.today.day%>日の行事は...</h1>
<br>
<br>
<li style="list-style: none;">
<% @naiyou.each do |naiyou| %>
<ul>
  <font color='yellow' size="6"><%= naiyou.content %>があります
</ul>
<%end%>
<% if @naiyou.length == 0 %>
<ul>
  <font color='yellow' size="6">ありません
</ul>
<%end%>
</li>


<br>
<br>
<br>
<br>
<font color='white' size="5"><%= link_to 'TOP画面へ' , '/' , :style=>"color:white;" %>
<br>
<font color='white' size="5"><%= link_to '行事の追加等（教員限定）', events_path , :style=>"color:white;" %>