config/routes.rb
Rails.application.routes.draw do
  resources :timetables
  get 'talks/index'
  post 'talks/update', to: 'talks#update', as: 'talk_update'

  resources :calendars
  get 'sessions/new'

  get 'events/top'
  resources :infos
  resources :events
  get 'classroom/top/:nen/:room' => 'classroom#top'
  #get 'home/top'
  get '/', to: 'home#top'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/calendar.rb
class Calendar < ApplicationRecord
    #validates :year, :filename, uniqueness: true
    validates :year, format: /[0-9]{4}/
end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController
  before_action :set_calendar, only: [:show, :edit, :update, :destroy]
  before_action :user_logged_in?, except: :index

  layout 'kokuban'



  # GET /calendars
  # GET /calendars.json
  def index
    logout
    @nendo = Date.today.year
    if Date.today.month < 4
      @nendo = @nendo - 1
    end
    if Calendar.find_by(year: @nendo) == nil
      @nendo = 0
    end
  end

  # GET /calendars/1
  # GET /calendars/1.json
  def show

  end

  # GET /calendars/new
  def new
    @calendar = Calendar.new
  end

  # GET /calendars/1/edit
  def edit
  end

  # POST /calendars
  # POST /calendars.json
  def create
    @calendar = Calendar.find_by(year: calendar_params[:nendo].to_i)
    if @calendar == nil
      @calendar = Calendar.new(calendar_params)
    end
    @calendar.filename = calendar_params[:filename]
    if !calendar_params[:filename].present?
      @calendar.errors[:base] << 'ファイル名を入力してください'
      render 'new'
    elsif calendar_params[:filename].content_type != "application/pdf"
      @calendar.errors[:base] << 'PDF以外のファイルはアップロードできません'
      render 'new'
    else
      File.open("app/assets/images/pdf/calendar/#{@calendar.year}"+".pdf","w+b"){
        |f| f.write(calendar_params[:filename].read)
      } 
      @calendar.filename = @calendar.year.to_s + ".pdf" 



      respond_to do |format|
        if @calendar.save
          format.html { redirect_to @calendar, notice: '成功しました！' }
          format.json { render :show, status: :created, location: @calendar }
        else
          format.html { render :new }
          format.json { render json: @calendar.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /calendars/1
  # PATCH/PUT /calendars/1.json
  def update
    respond_to do |format|
      if @calendar.update(calendar_params)
        format.html { redirect_to @calendar, notice: 'Calendar was successfully updated.' }
        format.json { render :show, status: :ok, location: @calendar }
      else
        format.html { render :edit }
        format.json { render json: @calendar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /calendars/1
  # DELETE /calendars/1.json
  def destroy
    @calendar.destroy
    respond_to do |format|
      format.html { redirect_to calendars_url, notice: 'Calendar was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_calendar
      @calendar = Calendar.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def calendar_params
      params.require(:calendar).permit(:year, :filename)
    end
end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/views/calendars/_form.html.erb
<%= form_with(model: calendar, local: true) do |form| %>
  <% if calendar.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(calendar.errors.count, "error") %> prohibited this calendar from being saved:</h2>

      <ul>
      <% calendar.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
  <font color='white' size="3"><%= form.label :カレンダーPDF %>
    <%= form.file_field :filename %>
    <%= form.label :年度 %>
    <%= form.number_field :year, id: :calendar_year, maxlength: 4 %>
  </div>

  <div class="actions">
    <%= form.submit :更新%>
  </div>
<% end %>

app/views/calendars/edit.html.erb
<font size="6" , color="white">編集</font>
<br>
<br>

<%= render 'form', calendar: @calendar %>

<%= link_to '詳細', @calendar, :style=>"color:white;" %> |
<%= link_to '戻る', calendars_path, :style=>"color:white;" %>

app/views/calendars/index.html.erb
<p id="notice"><%= notice %></p>

<font color='white' size="6">年間カレンダー</font>

<% if @nendo != 0 %> 
<object data="<%= asset_path 'pdf/calendar/' + @nendo.to_s + '.pdf'%>" type="application/pdf" width="100%" height="650px"></object>
<% end %>


<br>
<font size="3"><%= link_to 'TOP画面へ' , '/', :style=>"color:white;"  %>

<br>
<%= link_to '登録（教員限定）', new_calendar_path , :style=>"color:white;"  %>

app/views/calendars/new.html.erb
<font color='white' size="6">新規登録</font>
<br>
<br>

<%= render 'form', calendar: @calendar %>

<%= link_to '戻る', calendars_path, :style=>"color:white;" %>

app/views/calendars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <font size="4" , color="white"><strong>年度:</strong>
  <%= @calendar.year %></font>
</p>

<%= link_to '編集', edit_calendar_path(@calendar), :style=>"color:white;" %> |
<%= link_to '戻る', calendars_path, :style=>"color:white;" %>