config/routes.rb
Rails.application.routes.draw do
  resources :timetables
  get 'talks/index'
  post 'talks/update', to: 'talks#update', as: 'talk_update'

  resources :calendars
  get 'sessions/new'

  get 'events/top'
  resources :infos
  resources :events
  get 'classroom/top/:nen/:room' => 'classroom#top'
  #get 'home/top'
  get '/', to: 'home#top'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/info.rb
class Info < ApplicationRecord
    
end

app/controllers/infos_controller.rb
class InfosController < ApplicationController
  layout 'kokuban'
  
  before_action :set_info, only: [:show, :edit, :update, :destroy]
  before_action :user_logged_in?, except: [:index, :show] 

  # GET /infos
  # GET /infos.json
  def index
    logout
    if !session[:croom_id]
        redirect_to '/'
    else
      @croom = Croom.find(session[:croom_id])
      @nen = @croom.grade
      @room = @croom.room
      @infos = Info.where(room_id: session[:croom_id]).order("created_at desc")
    end
  end

  # GET /infos/1
  # GET /infos/1.json
  def show
    logout
  end

  # GET /infos/new
  def new
    @info = Info.new
  end

  # GET /infos/1/edit
  def edit
  end

  # POST /infos
  # POST /infos.json

  
  def create
    filename = ""
    if info_params[:filename].present?
      ext = File.extname(info_params[:filename].original_filename) 
      filename = Date.today.to_time.strftime("%Y%m%d%s%F") + ext
    end
    @info = Info.new(info_params)
    @info.filename = filename
    @info.room_id = session[:croom_id]
    if !info_params[:filename].present?
      respond_to do |format|
        if @info.save
         format.html { redirect_to @info, notice: '成功しました。' }
         format.json { render :show, status: :created, location: @info }
        else
         format.html { render :new }
         format.json { render json: @info.errors, status: :unprocessable_entity }
        end
      end  
    elsif info_params[:filename].content_type != "image/jpeg" &&
          info_params[:filename].content_type != "image/png" &&
          info_params[:filename].content_type != "image/gif"
      logger.debug info_params[:filename].content_type
      @info.errors[:base] << 'jpg,png,gif以外のファイルはアップロードできません'
      render 'new'
    else   
     File.open("app/assets/images/info/" + filename,"w+b"){
        |f| f.write(info_params[:filename].read)
      } 
      @info.filename = filename 
      respond_to do |format|
       if @info.save
        format.html { redirect_to @info, notice: '成功しました。' }
        format.json { render :show, status: :created, location: @info }
       else
        format.html { render :new }
        format.json { render json: @info.errors, status: :unprocessable_entity }
       end
      end    
    end 
  end

  # PATCH/PUT /infos/1
  # PATCH/PUT /infos/1.json
  def update
     filename = ""
     if info_params[:filename].present?
       ext = File.extname(info_params[:filename].original_filename) 
       filename = Date.today.to_time.strftime("%Y%m%d%s%F") + ext
     end    
     @info = Info.new(info_params)
     @info.filename = filename
     @info.room_id = session[:croom_id] 
     if !info_params[:filename].present?       
       respond_to do |format|
        if @info.update(info_params)
           format.html { redirect_to @info, notice: '成功しました。' }
           format.json { render :show, status: :ok, location: @info }
         else
           format.html { render :edit }
           format.json { render json: @info.errors, status: :unprocessable_entity }
         end
       end
     elsif info_params[:filename].content_type != "image/jpeg" &&
           info_params[:filename].content_type != "image/png" &&
           info_params[:filename].content_type != "image/gif"
       logger.debug info_params[:filename].content_type
       @info.errors[:base] << 'jpg,png,gif以外のファイルはアップロードできません'
       render 'new'
     else   
      File.open("app/assets/images/info/" + filename,"w+b"){
         |f| f.write(info_params[:filename].read)
      } 
      @info.filename = filename 
      respond_to do |format|
       if @info.save
        format.html { redirect_to @info, notice: '成功しました。' }
        format.json { render :show, status: :created, location: @info }
       else
        format.html { render :new }
        format.json { render json: @info.errors, status: :unprocessable_entity }
       end
      end    
    end 
  end    

  # DELETE /infos/1
  # DELETE /infos/1.json
  def destroy
    @info.destroy
    respond_to do |format|
      format.html { redirect_to infos_url, notice: '削除しました。' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_info
      @info = Info.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def info_params
      params.require(:info).permit(:title, :content, :limit, :filename)
    end
end

app/helpers/infos_helper.rb
module InfosHelper
    def GetRemainDays(kigen)
        sa = (kigen - Date.today ).to_i 
        if sa < 0
            sa = ""
        end
        sa
    end

    def IsLimitNear(kigen, value)
        sa = (kigen - Date.today).to_i
        sa > -1 && sa < value
    end

    def Isnew(create, value)
        day = (Date.today - create.to_date).to_i
        day < value
    end    
end

app/views/infos/_form.html.erb
<%= form_with(model: info, local: true) do |form| %>
  <% if info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(info.errors.count, "error") %> prohibited this info from being saved:</h2>

      <ul>
      <% info.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
  <br>
  <font color='white' size="3">
    <%= form.label :タイトル %>
    <%= form.text_field :title, id: :info_title %>
  </div>

  <div class="field">
    <%= form.label :内容　%>
    <%= form.text_field :content, id: :info_content %>
  </div>

  <div class="field">
    <%= form.label :締め切り　%>
    <%= form.date_select :limit, id: :info_limit %>
  </div>

  <div class="field">
    <%= form.label :画像 %>
    <%= form.file_field :filename, id: :info_filename %>
  </div>

  <div class="assets">
    <%= form.submit :更新 %>
  </div>
<% end %>

app/views/infos/edit.html.erb
<font size="5" color="white">編集画面</font>

<%= render 'form', info: @info %>



<br>
<td><font size="4"><%= link_to '削除', info_path, method: :delete, data: { confirm: '本当にいいですか？' } , :style=>"color:white;" %></td>

app/views/infos/index.html.erb
<p id="notice"><%= notice %></p>

<font color="white" size="6">インフォメーション</font>
<div style="width: 100%; height:620px; overflow:auto;">   
 <table style= "border-spacing: 0;"  width="60%">
 <br>
  <thead>
    <tr>
      <th style="border-top:none; border-left:none; border-bottom:none;"></th>
      <th style="border: 1px solid white"><font color="white">タイトル</font></th>
      <th style="border: 1px solid white"><font color="white">締め切り</font></th>
      <th style="border: 1px solid white"><font color="white">締め切りまでの残りの日にち</font></th>
      
    </tr>
  </thead>
  
  <tbody>
    <% @infos.each do |info| %>
      <tr>
        <td style="border-top:none; border-left:none; border-bottom:none;" width="11%">  
          <% if Isnew(info.created_at, 4) %>
            <img src="<%= asset_path 'info/new.png'%>"width="100%">
          <% end %>
        </td> 
                  
        <td style="border: 1px solid white" width="25%"><font size"2"><%= link_to info.title, info, :style=>"color:white;" %></td>
        <td style="border: 1px solid white" width="25%"><center><font color="white" size="2"><%= info.limit.strftime("%Y年%m月%d日") %></font></center></td>
        <td style="border: 1px solid white"><font color ="white">
          <% if IsLimitNear(info.limit, 6) %>
            <font color="red">
          <% end %>
          <%= GetRemainDays(info.limit) %>
          <% if IsLimitNear(info.limit, 6) %>
            </font>  
          <% end %>
          </font>
        </td>        
      </tr>
    <% end %>
  </tbody>
 </table>
</div>
<br>
<font size="3"><%= link_to '追加画面へ', new_info_path, :style=>"color:white;" %>
<br>
<%= link_to 'クラス画面のページに戻る' ,'classroom/top/' + @nen.to_s + '/' + @room.to_s, :style=>"color:white;" %>

app/views/infos/new.html.erb
<font color="white" size="5">追加内容</font>

<%= render 'form', info: @info %>

<font size="4"><%= link_to '戻る', infos_path, :style=>"color:white;" %>

app/views/infos/show.html.erb
<p id="notice"><%= notice %></p>
<font color='white' size="5">確認画面</font>
<p>
<br>
<font color="white"><strong>タイトル:</strong>
  <%= @info.title %>
  </font>
</p>
<font color="white">
<p>
<strong>内容:</strong>
  <%= @info.content %>
</p>
</font>
<font color="white">
<p>
<strong>締め切り:</strong>
  <%= @info.limit.strftime("%Y年%m月%d日")%>
</p>
</font>
<font color="white">
<p>
<strong>締め切りまでの残りの日数:</strong>
  <%
   @sa = (@info.limit - Date.today ).to_i 
  %>
  <% if @sa > -1 %>
    <%= @sa %> 
  <% end%>
</p>
</font>

<p>
<font color="white"><strong>画像:</strong></font>
<div style="width: 100%; height:320px; overflow:auto;">
  <% if @info.filename.present?%>
    <% if File.exists?('app/assets/images/info/' + @info.filename) %>
      <img src="<%= asset_path 'info/' + @info.filename %>" width="40%">
    <% end %>
  <% end %>
</p>
</div>



<br>
<font size="3"><%= link_to '戻る', infos_path, :style=>"color:white;" %> </font>
<br>
<font size="3"><%= link_to '編集画面へ', edit_info_path(@info), :style=>"color:white;" %> </font>